laalou/Models/Cart.cs
using System;
using System.Collections.Generic;

namespace laalou.Models;

public partial class Cart
{
    public int Id { get; set; }

    public string? UserId { get; set; }

    public int? ProductId { get; set; }

    public int? Qty { get; set; }

    public virtual Produit? Product { get; set; }

    internal void AddToCart(int productId, int quantity)
    {
        throw new NotImplementedException();
    }
}

laalou/Models/Category.cs
using System;
using System.Collections.Generic;

namespace laalou.Models;

public partial class Category
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Photo { get; set; }

    public string? Description { get; set; }

    public virtual ICollection<Produit> Produits { get; set; } = new List<Produit>();
}

laalou/Models/ErrorViewModel.cs
namespace laalou.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

laalou/Models/LaalouContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace laalou.Models;

public partial class LaalouContext : DbContext
{
   

    public LaalouContext(DbContextOptions<LaalouContext> options):base(options)
    {
            }



    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Produit> Produits { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

/*    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Server=REBROUB\\MSSQLSERVER01;Database=laalou;TrustServerCertificate=True;Trusted_Connection=True;");
*/
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cart>(entity =>
        {
            entity.ToTable("Cart");

            entity.Property(e => e.Id).HasColumnName("id");

            entity.HasOne(d => d.Product).WithMany(p => p.Carts)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_Cart_Produit");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.ToTable("Category");

            entity.Property(e => e.Id).HasColumnName("id");
        });

        modelBuilder.Entity<Produit>(entity =>
        {
            entity.ToTable("Produit");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Prix).HasColumnType("decimal(18, 0)");

            entity.HasOne(d => d.Cat).WithMany(p => p.Produits)
                .HasForeignKey(d => d.Catid)
                .HasConstraintName("FK_Produit_Category");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.ToTable("Review");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Email).HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

laalou/Models/Produit.cs
using System;
using System.Collections.Generic;

namespace laalou.Models;

public partial class Produit
{
    public int Id { get; set; }

    public string? Nom { get; set; }

    public string? Description { get; set; }

    public decimal? Prix { get; set; }

    public int? Catid { get; set; }

    public string? Photo { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual Category? Cat { get; set; }
}

laalou/Models/Review.cs
using System;
using System.Collections.Generic;

namespace laalou.Models;

public partial class Review
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Email { get; set; }

    public string? Subject { get; set; }

    public string? Description { get; set; }
}

laalou/Controllers/AdmController.cs
using laalou.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace laalou.Controllers
{
    public class AdmController : Controller
    {
        // GET: AdmController
      

        private readonly LaalouContext _db;
        public AdmController(LaalouContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            
            var cats = _db.Produits.ToList();
            return View(cats);

        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Produit obj)
        {
            if (ModelState.IsValid)
            {
                _db.Produits.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();

        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var Produits = _db.Produits.Find(id);
            if (Produits == null)
            {
                return NotFound();
            }
            return View(Produits);
        }

        [HttpPost]
        public IActionResult Edit(Produit obj)
        {
            if (ModelState.IsValid)
            {
                var OldCategory = _db.Produits.Find(obj.Id);
                if (OldCategory == null)
                {
                    return NotFound();
                }
                OldCategory.Nom = obj.Nom;
                OldCategory.Prix = obj.Prix;
                OldCategory.Photo = obj.Photo;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        public IActionResult Delete(int id)
        {
            var Produit = _db.Produits.Find(id);
            if (Produit == null)
            {
                return NotFound();
            }
            _db.Produits.Remove(Produit);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }














        // GET: AdmController/Details/5


    }
}

laalou/Views/Adm/Create.cshtml
@model Produit;
@{
    ViewData["Title"] = "Create/Adm";
}

<form asp-action="Create" methode="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-bg-danger-primary text-center">Create A Scenes</h2>
            <hr />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Nom"></label>
            <input asp-for="Nom" class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Description"></label>
            <input asp-for="Description" type="text" class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Photo"></label>
            <input asp-for="Photo" type="text" class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Prix"></label>
            <input asp-for="Prix" type="text" class="form-control" />
        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Category" asp-action="Index" class="btn btn-outline-secondary border" style="width.150px">
                    Back to List
                </a>
            </div>
        </div>


    </div>
</form>

laalou/Views/Adm/Delete.cshtml
@model Produit;


<p>Delete the Object</p>

laalou/Views/Adm/Edit.cshtml
@model Produit;


<form asp-action="Edit" methode="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-bg-danger-primary text-center">Edit Scenes</h2>
            <hr />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Nom"></label>
            <input asp-for="Nom" class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Prix"></label>
            <input asp-for="Prix" type="text" class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Photo"></label>
            <input asp-for="Photo" type="text" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Photo" class="control-label"></label>
            <input type="file" name="file" class="form-control" />
        </div>
        <div class="form-group">
            <img src="@Model.Photo" width="100%"
                 style="border-radius:5px; border:1px solid #bbb9b9" />
        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary" style="width:150px">Edit</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Adm" asp-action="index" class="btn btn-outline-secondary border" style="width.150px">
                    Back to List
                </a>
            </div>
        </div>


    </div>
</form>

laalou/Views/Adm/Index.cshtml
@model List<laalou.Models.Produit>
@{
    ViewData["Title"] = "Index Page";
}

<div class="row pb-3">
    @foreach (var product in Model)
    {
        <div class="col-lg-3 col-sm-6">
            <div class="row p-2">
                <div class="col-12 p-1">
                    <div class="card border-0 p-3 shadow border-top border-5 rounded">
                        <img src="~/images/@product.Photo" class="card-img-top rounded" />
                        <div class="card-body pb-0">
                            <div class="pb-1">
                                <p class="card-title h5 text-dark opacity-75 text-uppercase text-center">@product.Nom</p>
                                <p class="card-title text-warning text-center">by <b>@product.Description</b></p>
                            </div>
                            <div class="pb-1">
                                <p class="text-dark text-opacity-75 text-center mb-0">List Price:<span class="text-decoration-line-through">@product.Prix</span></p>
                            </div>

                        </div>
                        <div>
                            <a asp-action="Edit"
                               asp-route-productId="~/images/@product.Id"
                               class="btn btn-primary bg-gradient border-0 form-control">
                                Edite
                            </a>
                            <a asp-action="Delete"
                               asp-route-productId="~/images/@product.Id"
                               class="btn btn-primary bg-gradient border-0 form-control">
                                Detelet
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }


</div>

laalou/Views/Home/Cart.cshtml
<main class="page">
	<section class="shopping-cart dark">
		<div class="container">
			<div class="content">
				<div class="row">
					<div class="col-md-12 col-lg-8">
						<div class="items">
							<div class="product">
								<div class="row">
									<div class="col-md-3">
										<img class="img-fluid mx-auto d-block image" src="~/assetscart/img/image.jpg">
									</div>
									<div class="col-md-8">
										<div class="info">
											<div class="row">
												<div class="col-md-5 product-name">
													<div class="product-name">
														<a href="#">Lorem Ipsum dolor</a>
														<div class="product-info">
															<div>Display: <span class="value">5 inch</span></div>
									
														</div>
													</div>
												</div>
												<div class="col-md-4 quantity">
													<label for="quantity">Quantity:</label>
													<input id="quantity" type="number" value="1" class="form-control quantity-input">
												</div>
												<div class="col-md-3 price">
													<span>$120</span>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="product">
								<div class="row">
									<div class="col-md-3">
										<img class="img-fluid mx-auto d-block image" src="~/assetscartimg/image.jpg">
									</div>
									<div class="col-md-8">
										<div class="info">
											<div class="row">
												<div class="col-md-5 product-name">
													<div class="product-name">
														<a href="#">Lorem Ipsum dolor</a>
														<div class="product-info">
															<div>Display: <span class="value">5 inch</span></div>
															<div>RAM: <span class="value">4GB</span></div>
															<div>Memory: <span class="value">32GB</span></div>
														</div>
													</div>
												</div>
												<div class="col-md-4 quantity">
													<label for="quantity">Quantity:</label>
													<input id="quantity" type="number" value="1" class="form-control quantity-input">
												</div>
												<div class="col-md-3 price">
													<span>$120</span>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="product">
								<div class="row">
									<div class="col-md-3">
										<img class="img-fluid mx-auto d-block image" src="~/assetscart/img/image.jpg">
									</div>
									<div class="col-md-8">
										<div class="info">
											<div class="row">
												<div class="col-md-5 product-name">
													<div class="product-name">
														<a href="#">Lorem Ipsum dolor</a>
														<div class="product-info">
															<div>Display: <span class="value">5 inch</span></div>
															<div>RAM: <span class="value">4GB</span></div>
															<div>Memory: <span class="value">32GB</span></div>
														</div>
													</div>
												</div>
												<div class="col-md-4 quantity">
													<label for="quantity">Quantity:</label>
													<input id="quantity" type="number" value="1" class="form-control quantity-input">
												</div>
												<div class="col-md-3 price">
													<span>$120</span>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
                        </div>
					</div>
					<div class="col-md-12 col-lg-4">
						<div class="summary">
							<h3>Summary</h3>
							<div class="summary-item"><span class="text">Subtotal</span><span class="price">$360</span></div>
							<div class="summary-item"><span class="text">Discount</span><span class="price">$0</span></div>
							<div class="summary-item"><span class="text">Shipping</span><span class="price">$0</span></div>
							<div class="summary-item"><span class="text">Total</span><span class="price">$360</span></div>
							<button type="button" class="btn btn-primary btn-lg btn-block">Checkout</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</main>

laalou/Views/Home/Category.cshtml
@model List<laalou.Models.Category>

<section id="services" class="services section-bg">
    <div class="container" data-aos="fade-up">
        <div class="section-title">
            <h2>Category</h2>
        </div>

        <div class="row gy-4">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
                    <div class="icon-box iconbox-blue" style="width: 100% !important;">
                        <div class="icon">
                            <svg width="100" height="100" viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">
                                <path stroke="none" stroke-width="0" fill="#f5f5f5" d="M300,521.0016835830174C376.1290562159157,517.8887921683347,466.0731472004068,529.7835943286574,510.70327084640275,468.03025145048787C554.3714126377745,407.6079735673963,508.03601936045806,328.9844924480964,491.2728898941984,256.3432110539036C474.5976632858925,184.082847569629,479.9380746630129,96.60480741107993,416.23090153303,58.64404602377083C348.86323505073057,18.502131276798302,261.93793281208167,40.57373210992963,193.5410806939664,78.93577620505333C130.42746243093433,114.334589627462,98.30271207620316,179.96522072025542,76.75703585869454,249.04625023123273C51.97151888228291,328.5150500222984,13.704378332031375,421.85034740162234,66.52175969318436,486.19268352777647C119.04800174914682,550.1803526380478,217.28368757567262,524.383925680826,300,521.0016835830174"></path>
                            </svg>
                            <i class="bx @item.Photo"></i>
                        </div>
                        <h4><a href="@Url.Action("listeprod", "Home", new { id = item.Id })">@item.Name</a></h4>
                        <p>@item.Description</p>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

laalou/Views/Home/Index.cshtml
@model List<laalou.Models.Produit>

@{
    ViewData["Title"] = "Home Page";
}

<section id="billboard" class="position-relative overflow-hidden bg-light-blue">
    <div class="swiper main-swiper">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <div class="container">
                    <div class="row d-flex align-items-center">
                        <div class="col-md-6">
                            <div class="banner-content">
                                <h1 class="display-2 text-uppercase text-dark pb-5">Your Products Are Great.</h1>
                                <a href="shop.html" class="btn btn-medium btn-dark text-uppercase btn-rounded-none">Shop Product</a>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="image-holder">
                                <img src="images/banner-image.png" alt="banner">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="container">
                    <div class="row d-flex flex-wrap align-items-center">
                        <div class="col-md-6">
                            <div class="banner-content">
                                <h1 class="display-2 text-uppercase text-dark pb-5">Technology Hack You Won't Get</h1>
                                <a href="shop.html" class="btn btn-medium btn-dark text-uppercase btn-rounded-none">Shop Product</a>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="image-holder">
                                <img src="images/banner-image.png" alt="banner">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="swiper-icon swiper-arrow swiper-arrow-prev">
        <svg class="chevron-left">
            <use xlink:href="#chevron-left" />
        </svg>
    </div>
    <div class="swiper-icon swiper-arrow swiper-arrow-next">
        <svg class="chevron-right">
            <use xlink:href="#chevron-right" />
        </svg>
    </div>
</section>
<!-------------------------------------------------------------------------------------->

<section id="mobile-products" class="product-store position-relative padding-large no-padding-top">
    <div class="container">
        <div class="row">
            <div class="display-header d-flex justify-content-between pb-3">
                <h2 class="display-7 text-dark text-uppercase">Mobile Products</h2>
                <div class="btn-right">
                    <a href="@Url.Action("Category", "Home", new { category = "mobile" })" class="btn btn-medium btn-normal text-uppercase">Go to Mobile Category</a>
                </div>
            </div>
            <div class="swiper product-swiper">
                <div class="swiper-wrapper">
                    @foreach (var item in Model)
                    {
                        if (item.Catid == 1) // Afficher uniquement les images avec CatId = 1
                        {
                            <div class="swiper-slide">
                                <div class="product-card position-relative">
                                    <div class="image-holder">
                                        <a href="@Url.Action("Privacy", "Home", new { id = item.Id })">
                                            <img src="~/images/@item.Photo" alt="product-item" class="img-fluid">
                                        </a>
                                    </div>
                                    <div class="cart-concern position-absolute">
                                        <div class="cart-button d-flex">
                                            <a href="@Url.Action("AddToCart", "Home", new { id = item.Id })" class="btn btn-medium btn-black">Add to Cart<svg class="cart-outline"><use xlink:href="#cart-outline"></use></svg></a>
                                        </div>
                                    </div>
                                    <div class="card-detail d-flex justify-content-between align-items-baseline pt-3">
                                        <h3 class="card-title text-uppercase">
                                            <a href="@Url.Action("Privacy", "Home", new { id = item.Id })">@item.Nom</a>
                                        </h3>
                                        <span class="item-price text-primary">@item.Prix</span>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="swiper-pagination position-absolute text-center"></div>
</section>


<section id="smart-watches" class="product-store padding-large position-relative">
    <div class="container">
        <div class="row">
            <div class="display-header d-flex justify-content-between pb-3">
                <h2 class="display-7 text-dark text-uppercase">Smart Watches</h2>
                <div class="btn-right">
                    <a href="@Url.Action("Category", "Home", new { category = "watches" })" class="btn btn-medium btn-normal text-uppercase">Go to Watches Category</a>
                </div>
            </div>
            <div class="swiper product-watch-swiper">
                <div class="swiper-wrapper">
                    @foreach (var item in Model)
                    {
                        if (item.Catid == 2) // Afficher uniquement les images avec CatId = 2 pour les montres
                        {
                            <div class="swiper-slide">
                                <div class="product-card position-relative">
                                    <div class="image-holder">
                                        <a href="@Url.Action("Privacy", "Home", new { id = item.Id })">
                                            <img src="~/images/@item.Photo" alt="product-item" class="img-fluid">
                                        </a>
                                    </div>
                                    <div class="cart-concern position-absolute">
                                        <div class="cart-button d-flex">
                                            <a href="@Url.Action("AddToCart", "Home", new { id = item.Id })" class="btn btn-medium btn-black">Add to Cart<svg class="cart-outline"><use xlink:href="#cart-outline"></use></svg></a>
                                        </div>
                                    </div>
                                    <div class="card-detail d-flex justify-content-between align-items-baseline pt-3">
                                        <h3 class="card-title text-uppercase">
                                            <a href="@Url.Action("Privacy", "Home", new { id = item.Id })">@item.Nom</a>
                                        </h3>
                                        <span class="item-price text-primary">@item.Prix</span>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="swiper-pagination position-absolute text-center"></div>
</section>

<section id="latest-blog" class="padding-large">
    <div class="container">
        <div class="row">
            <div class="display-header d-flex justify-content-between pb-3">
                <h2 class="display-7 text-dark text-uppercase">Latest Posts</h2>
                <div class="btn-right">
                    <a href="@Url.Action("Blog", "Home")" class="btn btn-medium btn-normal text-uppercase">Read Blog</a>
                </div>
            </div>
            <div class="post-grid d-flex flex-wrap justify-content-between">
                @foreach (var post in Model)
                {
                    if (post.Catid == 3 || post.Catid == 4 || post.Catid == 5) // Afficher uniquement les images avec CatId = 3, 4 ou 5
                    {
                        <div class="col-lg-4 col-sm-12">
                            <div class="card border-none me-3">
                                <div class="card-image">
                                    <a href="@Url.Action("Privacy", "Home", new { id = post.Id })">
                                        <img src="~/images/@post.Photo" alt="post-item" class="img-fluid">
                                    </a>
                                </div>
                            </div>
                            <div class="card-body text-uppercase">
                                <div class="card-meta text-muted">
                                    <span class="meta-date">@post.Nom</span>
                                    <span class="meta-category">- @post.Description</span>
                                </div>
                               
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</section>

laalou/Views/Home/listeprod.cshtml
@model List<laalou.Models.Produit>

<section id="portfolio" class="portfolio">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>Portfolio</h2>
        </div>

        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <ul id="portfolio-flters">
                    <li data-filter="*" class="filter-active">All</li>
                    @foreach (var item in Model.Select(p => p.Catid).Distinct())
                    {
                        <li data-filter=".filter-@item">@(item == 1 ? "MOBILE" : item == 2 ? "Smart WATCHE" : item == 3 ? "Camera" : item == 4 ? "Airpods" : item == 5 ? "Playstation" : "P")</li>
                    }
                </ul>
            </div>
        </div>

        <div class="row portfolio-container">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-md-6 portfolio-item filter-@item.Catid">
                    <div class="portfolio-wrap">
                        <a href="@Url.Action("Privacy", "Home", new { id = item.Id })">
                            <!-- Ajoutez ce lien autour de l'image -->
                            <img src="~/images/@item.Photo" class="img-fluid" alt="">
                        </a>
                        <div class="portfolio-info">
                            <h4>@item.Nom</h4>
                            <p>@(item.Catid == 1 ? "Mobiles" : item.Catid == 2 ? "Smart Watches" : item.Catid == 3 ? "Camera" : item.Catid == 4 ? "Airpods" : item.Catid == 5 ? "Playstation" : "P")</p>
                        </div>
                        <div class="portfolio-links">
                            <a href="~/images/@item.Photo" data-gallery="portfolioGallery" class="portfolio-lightbox" title="@item.Nom"><i class="bx bx-plus"></i></a>
                            <a href="@Url.Action("Privacy", "Home", new { id = item.Id })" title="More Details"><i class="bx bx-link"></i></a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>